# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 08:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170530_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 30, 8, 4, 34, 264157, tzinfo=utc), editable=False, verbose_name='date published'),
        ),
    ]
