# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 08:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 30, 8, 8, 34, 819066, tzinfo=utc), editable=False),
        ),
    ]
