# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170530_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 12, 30, 49, 52993, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='edit_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 12, 30, 49, 53036, tzinfo=utc), editable=False),
        ),
    ]
