# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170531_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 13, 16, 22, 466851, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='edit_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 13, 16, 22, 466892, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='classification',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Classification'),
            preserve_default=False,
        ),
    ]
