# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170531_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=300)),
                ('date', models.DateTimeField(verbose_name='comment time')),
                ('name', models.CharField(max_length=50, verbose_name='name the comment belongs to')),
            ],
        ),
        migrations.RenameModel(
            old_name='Classification',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='classification_field',
            new_name='category_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='classification',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='headline',
        ),
        migrations.RemoveField(
            model_name='post',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='edit_time',
        ),
        migrations.AddField(
            model_name='post',
            name='modification_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
