# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170602_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modification_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
