# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170602_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
